// <auto-generated />
using Dondurmacf.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dondurmacf.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703171630_ReinitAll")]
    partial class ReinitAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dondurmacf.Model.DondurmaTur", b =>
                {
                    b.Property<int>("TurNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurNo"));

                    b.Property<int?>("EkleyenKullaniciNo")
                        .HasColumnType("int");

                    b.Property<int>("Fiyat")
                        .HasColumnType("int");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunNo")
                        .HasColumnType("int");

                    b.HasKey("TurNo");

                    b.HasIndex("EkleyenKullaniciNo");

                    b.HasIndex("UrunNo");

                    b.ToTable("Turs");

                    b.HasData(
                        new
                        {
                            TurNo = 1,
                            EkleyenKullaniciNo = 1,
                            Fiyat = 50,
                            Tur = "Sade Maraş",
                            UrunNo = 1
                        },
                        new
                        {
                            TurNo = 2,
                            EkleyenKullaniciNo = 1,
                            Fiyat = 55,
                            Tur = "Çikolatalı",
                            UrunNo = 1
                        },
                        new
                        {
                            TurNo = 3,
                            EkleyenKullaniciNo = 1,
                            Fiyat = 60,
                            Tur = "Çilekli",
                            UrunNo = 2
                        },
                        new
                        {
                            TurNo = 4,
                            EkleyenKullaniciNo = 2,
                            Fiyat = 60,
                            Tur = "Limonlu",
                            UrunNo = 2
                        },
                        new
                        {
                            TurNo = 5,
                            EkleyenKullaniciNo = 2,
                            Fiyat = 75,
                            Tur = "Antep Fıstıklı",
                            UrunNo = 3
                        },
                        new
                        {
                            TurNo = 6,
                            EkleyenKullaniciNo = 2,
                            Fiyat = 80,
                            Tur = "Karamelli Bisküvili",
                            UrunNo = 3
                        },
                        new
                        {
                            TurNo = 7,
                            EkleyenKullaniciNo = 3,
                            Fiyat = 70,
                            Tur = "Vanilyalı Kurabiyeli",
                            UrunNo = 1
                        },
                        new
                        {
                            TurNo = 8,
                            EkleyenKullaniciNo = 3,
                            Fiyat = 65,
                            Tur = "Kavunlu",
                            UrunNo = 2
                        },
                        new
                        {
                            TurNo = 9,
                            EkleyenKullaniciNo = 4,
                            Fiyat = 65,
                            Tur = "Böğürtlenli",
                            UrunNo = 2
                        },
                        new
                        {
                            TurNo = 10,
                            EkleyenKullaniciNo = 1,
                            Fiyat = 85,
                            Tur = "Belçika Çikolatalı",
                            UrunNo = 3
                        },
                        new
                        {
                            TurNo = 11,
                            EkleyenKullaniciNo = 4,
                            Fiyat = 75,
                            Tur = "Şekersiz Vanilyalı",
                            UrunNo = 4
                        },
                        new
                        {
                            TurNo = 12,
                            EkleyenKullaniciNo = 3,
                            Fiyat = 80,
                            Tur = "Vegan Hindistan Cevizli",
                            UrunNo = 4
                        },
                        new
                        {
                            TurNo = 13,
                            EkleyenKullaniciNo = 2,
                            Fiyat = 95,
                            Tur = "Dondurmalı Helva",
                            UrunNo = 5
                        },
                        new
                        {
                            TurNo = 14,
                            EkleyenKullaniciNo = 1,
                            Fiyat = 110,
                            Tur = "Dondurmalı Sufle",
                            UrunNo = 5
                        });
                });

            modelBuilder.Entity("Dondurmacf.Model.Kullanici", b =>
                {
                    b.Property<int>("KullaniciNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciNo"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciNo");

                    b.ToTable("Kullanicis");

                    b.HasData(
                        new
                        {
                            KullaniciNo = 1,
                            AdSoyad = "Esra Admin",
                            KullaniciAdi = "admin",
                            Sifre = "123"
                        },
                        new
                        {
                            KullaniciNo = 2,
                            AdSoyad = "Canan Personel",
                            KullaniciAdi = "user",
                            Sifre = "123"
                        },
                        new
                        {
                            KullaniciNo = 3,
                            AdSoyad = "Ömer Denetleyici",
                            KullaniciAdi = "supervisor",
                            Sifre = "123"
                        },
                        new
                        {
                            KullaniciNo = 4,
                            AdSoyad = "Aylin Kasiyer",
                            KullaniciAdi = "cashier",
                            Sifre = "123"
                        });
                });

            modelBuilder.Entity("Dondurmacf.Model.Urun", b =>
                {
                    b.Property<int>("UrunNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunNo"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunNo");

                    b.ToTable("Uruns");

                    b.HasData(
                        new
                        {
                            UrunNo = 1,
                            Aciklama = "Geleneksel lezzetler",
                            UrunAdi = "Klasik Dondurmalar"
                        },
                        new
                        {
                            UrunNo = 2,
                            Aciklama = "Taze meyvelerden üretilen dondurmalar",
                            UrunAdi = "Meyveli Dondurmalar"
                        },
                        new
                        {
                            UrunNo = 3,
                            Aciklama = "Özel tarifler ve zengin içerikler",
                            UrunAdi = "Premium Dondurmalar"
                        },
                        new
                        {
                            UrunNo = 4,
                            Aciklama = "Şekersiz ve bitkisel sütlü seçenekler",
                            UrunAdi = "Diyet & Vegan"
                        },
                        new
                        {
                            UrunNo = 5,
                            Aciklama = "Dondurma eşliğinde sunulan lezzetler",
                            UrunAdi = "Tatlılar & Kup"
                        });
                });

            modelBuilder.Entity("Dondurmacf.Model.DondurmaTur", b =>
                {
                    b.HasOne("Dondurmacf.Model.Kullanici", "EkleyenKullanici")
                        .WithMany()
                        .HasForeignKey("EkleyenKullaniciNo");

                    b.HasOne("Dondurmacf.Model.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("Urun");
                });
#pragma warning restore 612, 618
        }
    }
}
