// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBooking.Data;

#nullable disable

namespace TicketBooking.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBooking.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Canlı müzik, konserler ve festivaller",
                            IsActive = true,
                            Name = "Konser"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tiyatro oyunları ve sahne sanatları",
                            IsActive = true,
                            Name = "Tiyatro"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Futbol, basketbol ve diğer spor müsabakaları",
                            IsActive = true,
                            Name = "Spor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vizyondaki filmler ve özel gösterimler",
                            IsActive = true,
                            Name = "Sinema"
                        });
                });

            modelBuilder.Entity("TicketBooking.Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 500,
                            Capacity = 500,
                            CategoryId = 1,
                            Date = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Tarkan, en sevilen şarkılarıyla Harbiye Açıkhava Sahnesi'nde hayranlarıyla buluşuyor.",
                            ImageUrl = "/images/tarkan.jpg",
                            Location = "Harbiye Cemil Topuzlu Açıkhava Tiyatrosu, İstanbul",
                            Price = 1500.00m,
                            Title = "Tarkan Harbiye Konseri"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 300,
                            Capacity = 300,
                            CategoryId = 2,
                            Date = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Cem Yılmaz, yeni stand-up gösterisi ile Zorlu PSM'de kahkaha dolu bir gece sunuyor.",
                            ImageUrl = "/images/cemyilmaz.jpg",
                            Location = "Zorlu PSM - Turkcell Sahnesi, İstanbul",
                            Price = 1200.00m,
                            Title = "Cem Yılmaz - CMXXIV"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 1000,
                            Capacity = 1000,
                            CategoryId = 3,
                            Date = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Trendyol Süper Lig dev derbi heyecanı RAMS Park'ta yaşanıyor.",
                            ImageUrl = "/images/derbi.jpg",
                            Location = "RAMS Park, İstanbul",
                            Price = 2500.00m,
                            Title = "Galatasaray - Fenerbahçe Derbisi"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 100,
                            Capacity = 100,
                            CategoryId = 4,
                            Date = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Christopher Nolan'ın efsanevi yapıtı Interstellar, dev perdede sinemaseverlerle buluşuyor.",
                            ImageUrl = "/images/interstellar.jpg",
                            Location = "Kadıköy Sineması, İstanbul",
                            Price = 200.00m,
                            Title = "Interstellar Özel Gösterim"
                        });
                });

            modelBuilder.Entity("TicketBooking.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketBooking.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "admin@biletal.com",
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "esra@gmail.com",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Role = "User",
                            Username = "esra"
                        });
                });

            modelBuilder.Entity("TicketBooking.Core.Entities.Event", b =>
                {
                    b.HasOne("TicketBooking.Core.Entities.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TicketBooking.Core.Entities.Ticket", b =>
                {
                    b.HasOne("TicketBooking.Core.Entities.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketBooking.Core.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBooking.Core.Entities.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TicketBooking.Core.Entities.Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketBooking.Core.Entities.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
